In [1]:
# initial run through of project

In [2]:
# import necessary libraries

import pandas as pd

In [3]:
# scraping data 

titles = ['practice-1', 'practice-2', 'practice-3', 'qualifying', 'race-result']
url = 'https://www.formula1.com/en/results.html/2020/races/1056/portugal/{}.html'

for title in titles:
    urls = url.format(title)
    print(urls)

https://www.formula1.com/en/results.html/2020/races/1056/portugal/practice-1.html
https://www.formula1.com/en/results.html/2020/races/1056/portugal/practice-2.html
https://www.formula1.com/en/results.html/2020/races/1056/portugal/practice-3.html
https://www.formula1.com/en/results.html/2020/races/1056/portugal/qualifying.html
https://www.formula1.com/en/results.html/2020/races/1056/portugal/race-result.html

In [4]:
TwelveP1_2020 = 'https://www.formula1.com/en/results.html/2020/races/1056/portugal/practice-1.html'
TwelveP2_2020 ='https://www.formula1.com/en/results.html/2020/races/1056/portugal/practice-2.html'
TwelveP3_2020 ='https://www.formula1.com/en/results.html/2020/races/1056/portugal/practice-3.html'
TwelveQ_2020 ='https://www.formula1.com/en/results.html/2020/races/1056/portugal/qualifying.html'
TwelveRR_2020 ='https://www.formula1.com/en/results.html/2020/races/1056/portugal/race-result.html'

In [5]:
df_TwelveP1_2020 = pd.read_html(TwelveP1_2020, header=0)
df_TwelveP2_2020 = pd.read_html(TwelveP2_2020, header=0)
df_TwelveP3_2020 = pd.read_html(TwelveP3_2020, header=0)
df_TwelveQ_2020 = pd.read_html(TwelveQ_2020, header=0)
df_TwelveRR_2020 = pd.read_html(TwelveRR_2020, header=0)

df_TwelveP1_2020 = df_TwelveP1_2020[0]
df_TwelveP2_2020 = df_TwelveP2_2020[0]
df_TwelveP3_2020 = df_TwelveP3_2020[0]
df_TwelveQ_2020 = df_TwelveQ_2020[0]
df_TwelveRR_2020 = df_TwelveRR_2020[0]

In [6]:
df_TwelveP1_2020.drop(['Unnamed: 0', 'Unnamed: 8', 'No'], axis=1, inplace=True)
df_TwelveP2_2020.drop(['Unnamed: 0', 'Unnamed: 8', 'No'], axis=1, inplace=True)
df_TwelveP3_2020.drop(['Unnamed: 0', 'Unnamed: 8', 'No'], axis=1, inplace=True)
df_TwelveQ_2020.drop(['Unnamed: 0', 'Unnamed: 9', 'No'], axis=1, inplace=True)
df_TwelveRR_2020.drop(['Unnamed: 0', 'Unnamed: 8', 'No'], axis=1, inplace=True)

In [7]:
# df_TwelveP1_2020 = df_TwelveP1_2020.fillna(0)
# df_TwelveP2_2020 = df_TwelveP2_2020.fillna(0)
# df_TwelveP3_2020 = df_TwelveP3_2020.fillna(0)

In [8]:
portugal_GP = [df_TwelveP1_2020, df_TwelveP2_2020, df_TwelveP3_2020, df_TwelveQ_2020, df_TwelveRR_2020]

In [9]:
portugal_GP_0 = portugal_GP[0]
portugal_GP_1 = portugal_GP[1]
portugal_GP_2 = portugal_GP[2]
portugal_GP_3 = portugal_GP[3]
portugal_GP_4 = portugal_GP[4]

In [10]:
portugal_allP = pd.concat([portugal_GP_0, portugal_GP_1, portugal_GP_2])
portugal_allP = portugal_allP.groupby('Driver').Pos.sum()
portugal_allP = pd.DataFrame(portugal_allP)
portugal_allP.rename(columns = {'Pos': 'Pos_Practice'}, inplace = True)

In [11]:
portugalQ = portugal_GP_3.groupby('Driver').Pos.sum()
portugalQ = pd.DataFrame(portugalQ)
portugalQ.rename(columns = {'Pos': 'Pos_Qualifying'}, inplace = True)

In [12]:
portugalR = portugal_GP_4.groupby('Driver').Pos.sum()
portugalR = pd.DataFrame(portugalR)
portugalR.rename(columns = {'Pos': 'Pos_Race'}, inplace = True)

In [13]:
portugal_end = pd.concat([portugal_allP, portugalQ, portugalR], axis=1)

In [14]:
portugal_GP_0.sort_values(by=['Driver'], inplace=True)
portugal_GP_1.sort_values(by=['Driver'], inplace=True)
portugal_GP_2.sort_values(by=['Driver'], inplace=True)
portugal_GP_3.sort_values(by=['Driver'], inplace=True)
portugal_GP_4.sort_values(by=['Driver'], inplace=True)

In [15]:
portugal_dl = pd.merge(portugal_GP_0, portugal_GP_1, on='Driver', how='outer')
portugal_dl = pd.merge(portugal_dl, portugal_GP_2, on='Driver', how='outer')
portugal_dl = pd.merge(portugal_dl, portugal_GP_3, on='Driver', how='outer')
portugal_dl = pd.merge(portugal_dl, portugal_GP_4, on='Driver', how='outer')

In [16]:
change_dups = portugal_dl.columns.values.tolist()
change_dups

['Pos_x',
 'Driver',
 'Car_x',
 'Time_x',
 'Gap_x',
 'Laps_x',
 'Pos_y',
 'Car_y',
 'Time_y',
 'Gap_y',
 'Laps_y',
 'Pos_x',
 'Car_x',
 'Time',
 'Gap',
 'Laps_x',
 'Pos_y',
 'Car_y',
 'Q1',
 'Q2',
 'Q3',
 'Laps_y',
 'Pos',
 'Car',
 'Laps',
 'Time/Retired',
 'PTS']

In [17]:
def uniquify(change_dups):
    seen = set()
    
    for dup in change_dups:
        name = 1
        new_name = dup
        
        while new_name in seen:
            name += 1
            new_name = "{}_{}".format(dup, name)
            
        yield new_name
        seen.add(new_name)
        
list(uniquify(change_dups))

['Pos_x',
 'Driver',
 'Car_x',
 'Time_x',
 'Gap_x',
 'Laps_x',
 'Pos_y',
 'Car_y',
 'Time_y',
 'Gap_y',
 'Laps_y',
 'Pos_x_2',
 'Car_x_2',
 'Time',
 'Gap',
 'Laps_x_2',
 'Pos_y_2',
 'Car_y_2',
 'Q1',
 'Q2',
 'Q3',
 'Laps_y_2',
 'Pos',
 'Car',
 'Laps',
 'Time/Retired',
 'PTS']

In [18]:
portugal_dl = portugal_dl.set_axis(
['Pos_x',
 'Driver',
 'Car_x',
 'Time_x',
 'Gap_x',
 'Laps_x',
 'Pos_y',
 'Car_y',
 'Time_y',
 'Gap_y',
 'Laps_y',
 'Pos_x_2',
 'Car_x_2',
 'Time',
 'Gap',
 'Laps_x_2',
 'Pos_y_2',
 'Car_y_2',
 'Q1',
 'Q2',
 'Q3',
 'Laps_y_2',
 'Pos',
 'Car',
 'Laps',
 'Time/Retired',
 'PTS'], axis=1, inplace=False)

In [19]:
change_dups

['Pos_x',
 'Driver',
 'Car_x',
 'Time_x',
 'Gap_x',
 'Laps_x',
 'Pos_y',
 'Car_y',
 'Time_y',
 'Gap_y',
 'Laps_y',
 'Pos_x',
 'Car_x',
 'Time',
 'Gap',
 'Laps_x',
 'Pos_y',
 'Car_y',
 'Q1',
 'Q2',
 'Q3',
 'Laps_y',
 'Pos',
 'Car',
 'Laps',
 'Time/Retired',
 'PTS']

In [20]:
new_names = ['Pos1',
 'Driver1',
 'Car1',
 'Time1',
 'Gap1',
 'Laps1',
 'Pos2',
 'Car2',
 'Time2',
 'Gap2',
 'Laps2',
 'Pos3',
 'Car3',
 'Time3',
 'Gap3',
 'Laps3',
 'PosQ',
 'CarQ',
 'Q1_Q',
 'Q2_Q',
 'Q3_Q',
 'LapsQ',
 'PosRR',
 'CarRR',
 'LapsRR',
 'Time/Retired_RR',
 'PTS_RR']

In [21]:
portugal_dl.columns = ['Pos1',
 'Driver1',
 'Car1',
 'Time1',
 'Gap1',
 'Laps1',
 'Pos2',
 'Car2',
 'Time2',
 'Gap2',
 'Laps2',
 'Pos3',
 'Car3',
 'Time3',
 'Gap3',
 'Laps3',
 'PosQ',
 'CarQ',
 'Q1_Q',
 'Q2_Q',
 'Q3_Q',
 'LapsQ',
 'PosRR',
 'CarRR',
 'LapsRR',
 'Time/Retired_RR',
 'PTS_RR']

In [22]:
portugal_dl.drop(['Car2', 'Car3', 'CarQ', 'CarRR'], axis=1, inplace=True)

In [23]:
# portugal_dl = portugal_dl.fillna('n/a')

In [24]:
names_list = list(portugal_dl.columns)

new_names_list = []

for names in names_list:
    names = 'portugal_' + names
    new_names_list.append(names)
    
portugal_dl.columns = new_names_list

In [25]:
portugal_dl = portugal_dl[~portugal_dl['portugal_Time/Retired_RR'].isin(['DNF'])]

In [26]:
pd.options.mode.chained_assignment = None  # default='warn'
portugal_dl.drop(portugal_dl.columns[[4, 5, 8, 9, 12, 13, 18, 20, 21]], axis=1, inplace=True)

In [27]:
portugal_dl.drop(['portugal_Time1', 'portugal_Time2', 'portugal_Time3'], axis=1, inplace=True)

In [28]:
def qualifying_values(race):
    race.iloc[:, 6] = race.iloc[:, 6].apply(lambda x: 1 if not pd.isnull(x) else 0)
    race.iloc[:, 7] = race.iloc[:, 7].apply(lambda x: 1 if not pd.isnull(x) else 0)
    race.iloc[:, 8] = race.iloc[:, 8].apply(lambda x: 1 if not pd.isnull(x) else 0)

In [29]:
qualifying_values(portugal_dl)

In [30]:
portugal_dl

,portugal_Pos1,portugal_Driver1,portugal_Car1,portugal_Pos2,portugal_Pos3,portugal_PosQ,portugal_Q1_Q,portugal_Q2_Q,portugal_Q3_Q,portugal_PosRR,portugal_PTS_RR
0,5,Alexander Albon ALB,Red Bull Racing Honda,10,5,6,1,1,1,12,0
1,16,Antonio Giovinazzi GIO,Alfa Romeo Racing Ferrari,20,17,17,1,0,0,15,0
2,6,Carlos Sainz SAI,McLaren Renault,5,7,7,1,1,1,6,8
3,4,Charles Leclerc LEC,Ferrari,4,6,4,1,1,1,4,12
4,9,Daniel Ricciardo RIC,Renault,13,14,10,1,1,0,9,2
5,13,Daniil Kvyat KVY,AlphaTauri Honda,17,12,13,1,1,0,19,0
6,19,Esteban Ocon OCO,Renault,9,10,11,1,1,0,8,4
7,18,George Russell RUS,Williams Mercedes,11,15,14,1,1,0,14,0
8,14,Kevin Magnussen MAG,Haas Ferrari,16,18,19,1,0,0,16,0
9,8,Kimi Räikkönen RAI,Alfa Romeo Racing Ferrari,15,13,16,1,0,0,11,0
11,12,Lando Norris NOR,McLaren Renault,3,9,8,1,1,1,13,0
12,2,Lewis Hamilton HAM,Mercedes,8,2,1,1,1,1,1,26
13,3,Max Verstappen VER,Red Bull Racing Honda,2,3,3,1,1,1,3,15
14,20,Nicholas Latifi LAT,Williams Mercedes,14,19,20,1,0,0,18,0
15,10,Pierre Gasly GAS,AlphaTauri Honda,7,4,9,1,1,1,5,10
16,17,Romain Grosjean GRO,Haas Ferrari,18,20,18,1,0,0,17,0
17,11,Sebastian Vettel VET,Ferrari,6,11,15,1,1,0,10,1
18,7,Sergio Perez PER,Racing Point BWT Mercedes,12,8,5,1,1,1,7,6
19,1,Valtteri Bottas BOT,Mercedes,1,1,2,1,1,1,2,18

In [31]:
%store portugal_dl

Stored 'portugal_dl' (DataFrame)