In [1]:
# initial run through of project

In [2]:
# import necessary libraries

import pandas as pd

In [3]:
# scraping data 

titles = ['practice-1', 'qualifying', 'race-result']
url = 'https://www.formula1.com/en/results.html/2020/races/1057/italy/{}.html'

for title in titles:
    urls = url.format(title)
    print(urls)

https://www.formula1.com/en/results.html/2020/races/1057/italy/practice-1.html
https://www.formula1.com/en/results.html/2020/races/1057/italy/qualifying.html
https://www.formula1.com/en/results.html/2020/races/1057/italy/race-result.html

In [4]:
ThirteenP1_2020 = 'https://www.formula1.com/en/results.html/2020/races/1057/italy/practice-1.html'
ThirteenQ_2020 ='https://www.formula1.com/en/results.html/2020/races/1057/italy/qualifying.html'
ThirteenRR_2020 ='https://www.formula1.com/en/results.html/2020/races/1057/italy/race-result.html'

In [5]:
df_ThirteenP1_2020 = pd.read_html(ThirteenP1_2020, header=0)
df_ThirteenQ_2020 = pd.read_html(ThirteenQ_2020, header=0)
df_ThirteenRR_2020 = pd.read_html(ThirteenRR_2020, header=0)

df_ThirteenP1_2020 = df_ThirteenP1_2020[0]
df_ThirteenQ_2020 = df_ThirteenQ_2020[0]
df_ThirteenRR_2020 = df_ThirteenRR_2020[0]

In [6]:
df_ThirteenP1_2020.drop(['Unnamed: 0', 'Unnamed: 8', 'No'], axis=1, inplace=True)
df_ThirteenQ_2020.drop(['Unnamed: 0', 'Unnamed: 9', 'No'], axis=1, inplace=True)
df_ThirteenRR_2020.drop(['Unnamed: 0', 'Unnamed: 8', 'No'], axis=1, inplace=True)

In [7]:
# df_ThirteenP1_2020 = df_ThirteenP1_2020.fillna(0)

In [8]:
er_GP = [df_ThirteenP1_2020, df_ThirteenQ_2020, df_ThirteenRR_2020]

In [9]:
er_GP_0 = er_GP[0]
er_GP_1 = er_GP[1]
er_GP_2 = er_GP[2]

In [10]:
er_allP = er_GP[0]
er_allP = er_allP.groupby('Driver').Pos.sum()
er_allP = pd.DataFrame(er_allP)
er_allP.rename(columns = {'Pos': 'Pos_Practice'}, inplace = True)

In [11]:
erQ = er_GP_1.groupby('Driver').Pos.sum()
erQ = pd.DataFrame(erQ)
erQ.rename(columns = {'Pos': 'Pos_Qualifying'}, inplace = True)

In [12]:
erR = er_GP_2.groupby('Driver').Pos.sum()
erR = pd.DataFrame(erR)
erR.rename(columns = {'Pos': 'Pos_Race'}, inplace = True)

In [13]:
er_end = pd.concat([er_allP, erQ, erR], axis=1)

In [14]:
er_GP_0.sort_values(by=['Driver'], inplace=True)
er_GP_1.sort_values(by=['Driver'], inplace=True)
er_GP_2.sort_values(by=['Driver'], inplace=True)

In [15]:
er_dl = pd.merge(er_GP_0, er_GP_1, on='Driver', how='outer')
er_dl = pd.merge(er_dl, er_GP_2, on='Driver', how='outer')

In [16]:
change_dups = er_dl.columns.values.tolist()
change_dups

['Pos_x',
 'Driver',
 'Car_x',
 'Time',
 'Gap',
 'Laps_x',
 'Pos_y',
 'Car_y',
 'Q1',
 'Q2',
 'Q3',
 'Laps_y',
 'Pos',
 'Car',
 'Laps',
 'Time/Retired',
 'PTS']

In [17]:
def uniquify(change_dups):
    seen = set()
    
    for dup in change_dups:
        name = 1
        new_name = dup
        
        while new_name in seen:
            name += 1
            new_name = "{}_{}".format(dup, name)
            
        yield new_name
        seen.add(new_name)
        
list(uniquify(change_dups))

['Pos_x',
 'Driver',
 'Car_x',
 'Time',
 'Gap',
 'Laps_x',
 'Pos_y',
 'Car_y',
 'Q1',
 'Q2',
 'Q3',
 'Laps_y',
 'Pos',
 'Car',
 'Laps',
 'Time/Retired',
 'PTS']

In [18]:
er_dl = er_dl.set_axis(['Pos_x',
 'Driver',
 'Car_x',
 'Time',
 'Gap',
 'Laps_x',
 'Pos_y',
 'Car_y',
 'Q1',
 'Q2',
 'Q3',
 'Laps_y',
 'Pos',
 'Car',
 'Laps',
 'Time/Retired',
 'PTS'], axis=1, inplace=False)

In [19]:
change_dups

['Pos_x',
 'Driver',
 'Car_x',
 'Time',
 'Gap',
 'Laps_x',
 'Pos_y',
 'Car_y',
 'Q1',
 'Q2',
 'Q3',
 'Laps_y',
 'Pos',
 'Car',
 'Laps',
 'Time/Retired',
 'PTS']

In [20]:
new_names = ['Pos1',
 'Driver1',
 'Car1',
 'Time1',
 'Gap1',
 'Laps1',
 'PosQ',
 'CarQ',
 'Q1_Q',
 'Q2_Q',
 'Q3_Q',
 'LapsQ',
 'PosRR',
 'CarRR',
 'LapsRR',
 'Time/Retired_RR',
 'PTS_RR']

In [21]:
er_dl.columns = ['Pos1',
 'Driver1',
 'Car1',
 'Time1',
 'Gap1',
 'Laps1',
 'PosQ',
 'CarQ',
 'Q1_Q',
 'Q2_Q',
 'Q3_Q',
 'LapsQ',
 'PosRR',
 'CarRR',
 'LapsRR',
 'Time/Retired_RR',
 'PTS_RR']

In [22]:
er_dl.drop(['CarQ', 'CarRR'], axis=1, inplace=True)

In [23]:
# er_dl = er_dl.fillna('n/a')

In [24]:
names_list = list(er_dl.columns)

new_names_list = []

for names in names_list:
    names = 'er_' + names
    new_names_list.append(names)
    
er_dl.columns = new_names_list

In [25]:
er_dl = er_dl[~er_dl['er_Time/Retired_RR'].isin(['DNF'])]

In [26]:
er_dl

,er_Pos1,er_Driver1,er_Car1,er_Time1,er_Gap1,er_Laps1,er_PosQ,er_Q1_Q,er_Q2_Q,er_Q3_Q,er_LapsQ,er_PosRR,er_LapsRR,er_Time/Retired_RR,er_PTS_RR
0,9,Alexander Albon ALB,Red Bull Racing Honda,1:16.061,+1.335s,41,6,1:15.402,1:14.745,1:14.572,21,15,63,+57.284s,0
1,15,Antonio Giovinazzi GIO,Alfa Romeo Racing Ferrari,1:16.564,+1.838s,33,20,1:16.208,NaN,NaN,8,10,63,+26.398s,1
2,14,Carlos Sainz SAI,McLaren Renault,1:16.560,+1.834s,42,10,1:15.528,1:15.027,1:14.911,19,7,63,+20.230s,6
3,5,Charles Leclerc LEC,Ferrari,1:15.688,+0.962s,41,7,1:15.123,1:15.017,1:14.616,20,5,63,+19.111s,10
4,6,Daniel Ricciardo RIC,Renault,1:15.839,+1.113s,32,5,1:15.474,1:14.953,1:14.520,18,3,63,+14.320s,15
5,8,Daniil Kvyat KVY,AlphaTauri Honda,1:15.966,+1.240s,47,8,1:15.412,1:15.022,1:14.696,21,4,63,+15.141s,12
9,17,Kimi Räikkönen RAI,Alfa Romeo Racing Ferrari,1:16.684,+1.958s,43,18,1:15.953,NaN,NaN,10,9,63,+22.224s,2
10,10,Lance Stroll STR,Racing Point BWT Mercedes,1:16.082,+1.356s,42,15,1:15.822,1:15.494,NaN,16,13,63,+29.163s,0
11,16,Lando Norris NOR,McLaren Renault,1:16.671,+1.945s,45,9,1:15.274,1:15.051,1:14.814,17,8,63,+21.131s,4
12,1,Lewis Hamilton HAM,Mercedes,1:14.726,NaN,46,2,1:14.229,1:14.643,1:13.706,22,1,63,1:28:32.430,26
14,20,Nicholas Latifi LAT,Williams Mercedes,1:17.779,+3.053s,29,19,1:15.987,NaN,NaN,12,11,63,+27.135s,0
16,13,Romain Grosjean GRO,Haas Ferrari,1:16.550,+1.824s,42,16,1:15.918,NaN,NaN,10,14,63,+32.935s,0
17,12,Sebastian Vettel VET,Ferrari,1:16.167,+1.441s,40,14,1:15.571,1:15.385,NaN,20,12,63,+28.453s,0
18,11,Sergio Perez PER,Racing Point BWT Mercedes,1:16.109,+1.383s,42,11,1:15.407,1:15.061,NaN,16,6,63,+19.652s,8
19,3,Valtteri Bottas BOT,Mercedes,1:15.218,+0.492s,47,1,1:14.221,1:14.585,1:13.609,22,2,63,+5.783s,18

In [27]:
pd.options.mode.chained_assignment = None  # default='warn'
er_dl.drop(er_dl.columns[[4, 5, 10, 12, 13]], axis=1, inplace=True)

In [28]:
er_dl.drop(['er_Time1'], axis=1, inplace=True)

In [29]:
def qualifying_values(race):
    race.iloc[:, 4] = race.iloc[:, 4].apply(lambda x: 1 if not pd.isnull(x) else 0)
    race.iloc[:, 5] = race.iloc[:, 5].apply(lambda x: 1 if not pd.isnull(x) else 0)
    race.iloc[:, 6] = race.iloc[:, 6].apply(lambda x: 1 if not pd.isnull(x) else 0)

In [30]:
qualifying_values(er_dl)

In [31]:
er_dl

,er_Pos1,er_Driver1,er_Car1,er_PosQ,er_Q1_Q,er_Q2_Q,er_Q3_Q,er_PosRR,er_PTS_RR
0,9,Alexander Albon ALB,Red Bull Racing Honda,6,1,1,1,15,0
1,15,Antonio Giovinazzi GIO,Alfa Romeo Racing Ferrari,20,1,0,0,10,1
2,14,Carlos Sainz SAI,McLaren Renault,10,1,1,1,7,6
3,5,Charles Leclerc LEC,Ferrari,7,1,1,1,5,10
4,6,Daniel Ricciardo RIC,Renault,5,1,1,1,3,15
5,8,Daniil Kvyat KVY,AlphaTauri Honda,8,1,1,1,4,12
9,17,Kimi Räikkönen RAI,Alfa Romeo Racing Ferrari,18,1,0,0,9,2
10,10,Lance Stroll STR,Racing Point BWT Mercedes,15,1,1,0,13,0
11,16,Lando Norris NOR,McLaren Renault,9,1,1,1,8,4
12,1,Lewis Hamilton HAM,Mercedes,2,1,1,1,1,26
14,20,Nicholas Latifi LAT,Williams Mercedes,19,1,0,0,11,0
16,13,Romain Grosjean GRO,Haas Ferrari,16,1,0,0,14,0
17,12,Sebastian Vettel VET,Ferrari,14,1,1,0,12,0
18,11,Sergio Perez PER,Racing Point BWT Mercedes,11,1,1,0,6,8
19,3,Valtteri Bottas BOT,Mercedes,1,1,1,1,2,18

In [32]:
%store er_dl

Stored 'er_dl' (DataFrame)