In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from pandas_profiling import ProfileReport

In [2]:
%store -r austria_dl
%store -r styria_dl
%store -r hungary_dl
%store -r gb_dl
%store -r gb70_dl
%store -r spain_dl
%store -r belgium_dl
%store -r italy_dl
%store -r tuscany_dl
%store -r russia_dl
%store -r eifel_dl
%store -r portugal_dl
%store -r er_dl
%store -r turkey_dl
%store -r bahrain_dl
%store -r sakhir_dl
%store -r ad_dl

In [3]:
all_races = [austria_dl,
styria_dl,
hungary_dl,
gb_dl,
gb70_dl,
spain_dl,
belgium_dl,
italy_dl,
tuscany_dl,
russia_dl,
eifel_dl,
portugal_dl,
er_dl,
turkey_dl,
bahrain_dl,
sakhir_dl,
ad_dl]

In [4]:
def change_values(race):
    for col, row in race.iteritems():
        if isinstance(row[0], str):
            race.loc[race[col] == 'n/a', col] = 0
            race.loc[race[col] == 'NC', col] = 0
            race.loc[race[col] == 'DNF', col] = 0
            
def no_NA(race):
    race = race.replace(to_replace='n/a',
                value='0', inplace=True)
    
def no_NC(race):
    race = race.replace(to_replace='NC',
                value='0', inplace=True)
    
def no_DNF(race):
    race = race.replace(to_replace='DNF',
                value='0', inplace=True)
    
def no_DNS(race):
    race = race.replace(to_replace='DNS',
                value='0', inplace=True)
    
def no_lap(race):
    race = race.replace(to_replace='+1 lap', 
                value='0', inplace=True)
    
def no_laps(race):
    race = race.replace(to_replace='+2 laps', 
                value='0', inplace=True)

In [5]:
for race in all_races:
    no_NA(race)
    no_NC(race)
    no_DNF(race)
    no_DNS(race)
    no_lap(race)
    no_laps(race)

In [12]:
NAMES = austria_dl['austria_Driver1']

austria_dl.drop(['austria_Driver1', 'austria_Car1'], axis=1, inplace=True)
styria_dl.drop(['styria_Driver1', 'styria_Car1'], axis=1, inplace=True)
hungary_dl.drop(['hungary_Driver1', 'hungary_Car1'], axis=1, inplace=True)
gb_dl.drop(['gb_Driver1', 'gb_Car1'], axis=1, inplace=True)
gb70_dl.drop(['gb70_Driver1', 'gb70_Car1'], axis=1, inplace=True)
spain_dl.drop(['spain_Driver1', 'spain_Car1'], axis=1, inplace=True)
belgium_dl.drop(['belgium_Driver1', 'belgium_Car1'], axis=1, inplace=True)
italy_dl.drop(['italy_Driver1', 'italy_Car1'], axis=1, inplace=True)
tuscany_dl.drop(['tuscany_Driver1', 'tuscany_Car1'], axis=1, inplace=True)
russia_dl.drop(['russia_Driver1', 'russia_Car1'], axis=1, inplace=True)
eifel_dl.drop(['eifel_Driver1', 'eifel_Car1'], axis=1, inplace=True)
portugal_dl.drop(['portugal_Driver1', 'portugal_Car1'], axis=1, inplace=True)
er_dl.drop(['er_Driver1', 'er_Car1'], axis=1, inplace=True)
turkey_dl.drop(['turkey_Driver1', 'turkey_Car1'], axis=1, inplace=True)
bahrain_dl.drop(['bahrain_Driver1', 'bahrain_Car1'], axis=1, inplace=True)
sakhir_dl.drop(['sakhir_Driver1', 'sakhir_Car1'], axis=1, inplace=True)
ad_dl.drop(['ad_Driver1', 'ad_Car1'], axis=1, inplace=True)

In [7]:
# ad_dl.dtypes

In [8]:
# test = '+:.s'
# gone = lambda x: "" if x in ":.+s" else x
# message = filter(gone, test)
# "".join(message)

In [9]:
# austria_dl = austria_dl.replace({':':''}, regex=True)
# austria_dl = austria_dl.replace({'s':''}, regex=True)
# austria_dl = austria_dl.replace({'\+':''}, regex=True)
# austria_dl = austria_dl.replace({'\.':''}, regex=True)

In [10]:
# def remove_characters(race):
#         race = race.replace({':':''}, regex=True)
#         race = race.replace({'s':''}, regex=True)
#         race = race.replace({'\+':''}, regex=True)
#         race = race.replace({'\.':''}, regex=True)

In [14]:
austria_dl = austria_dl.replace({':':''}, regex=True)
austria_dl = austria_dl.replace({'s':''}, regex=True)
austria_dl = austria_dl.replace({'\+':''}, regex=True)
austria_dl = austria_dl.replace({'\.':''}, regex=True)

styria_dl = styria_dl.replace({':':''}, regex=True)
styria_dl = styria_dl.replace({'s':''}, regex=True)
styria_dl = styria_dl.replace({'\+':''}, regex=True)
styria_dl = styria_dl.replace({'\.':''}, regex=True)

hungary_dl = hungary_dl.replace({':':''}, regex=True)
hungary_dl = hungary_dl.replace({'s':''}, regex=True)
hungary_dl = hungary_dl.replace({'\+':''}, regex=True)
hungary_dl = hungary_dl.replace({'\.':''}, regex=True)

gb_dl = gb_dl.replace({':':''}, regex=True)
gb_dl = gb_dl.replace({'s':''}, regex=True)
gb_dl = gb_dl.replace({'\+':''}, regex=True)
gb_dl = gb_dl.replace({'\.':''}, regex=True)

gb70_dl = gb70_dl.replace({':':''}, regex=True)
gb70_dl = gb70_dl.replace({'s':''}, regex=True)
gb70_dl = gb70_dl.replace({'\+':''}, regex=True)
gb70_dl = gb70_dl.replace({'\.':''}, regex=True)

spain_dl = spain_dl.replace({':':''}, regex=True)
spain_dl = spain_dl.replace({'s':''}, regex=True)
spain_dl = spain_dl.replace({'\+':''}, regex=True)
spain_dl = spain_dl.replace({'\.':''}, regex=True)

belgium_dl = belgium_dl.replace({':':''}, regex=True)
belgium_dl = belgium_dl.replace({'s':''}, regex=True)
belgium_dl = belgium_dl.replace({'\+':''}, regex=True)
belgium_dl = belgium_dl.replace({'\.':''}, regex=True)

italy_dl = italy_dl.replace({':':''}, regex=True)
italy_dl = italy_dl.replace({'s':''}, regex=True)
italy_dl = italy_dl.replace({'\+':''}, regex=True)
italy_dl = italy_dl.replace({'\.':''}, regex=True)

tuscany_dl = tuscany_dl.replace({':':''}, regex=True)
tuscany_dl = tuscany_dl.replace({'s':''}, regex=True)
tuscany_dl = tuscany_dl.replace({'\+':''}, regex=True)
tuscany_dl = tuscany_dl.replace({'\.':''}, regex=True)

russia_dl = russia_dl.replace({':':''}, regex=True)
russia_dl = russia_dl.replace({'s':''}, regex=True)
russia_dl = russia_dl.replace({'\+':''}, regex=True)
russia_dl = russia_dl.replace({'\.':''}, regex=True)

eifel_dl = eifel_dl.replace({':':''}, regex=True)
eifel_dl = eifel_dl.replace({'s':''}, regex=True)
eifel_dl = eifel_dl.replace({'\+':''}, regex=True)
eifel_dl = eifel_dl.replace({'\.':''}, regex=True)

portugal_dl = portugal_dl.replace({':':''}, regex=True)
portugal_dl = portugal_dl.replace({'s':''}, regex=True)
portugal_dl = portugal_dl.replace({'\+':''}, regex=True)
portugal_dl = portugal_dl.replace({'\.':''}, regex=True)

er_dl = er_dl.replace({':':''}, regex=True)
er_dl = er_dl.replace({'s':''}, regex=True)
er_dl = er_dl.replace({'\+':''}, regex=True)
er_dl = er_dl.replace({'\.':''}, regex=True)

turkey_dl = turkey_dl.replace({':':''}, regex=True)
turkey_dl = turkey_dl.replace({'s':''}, regex=True)
turkey_dl = turkey_dl.replace({'\+':''}, regex=True)
turkey_dl = turkey_dl.replace({'\.':''}, regex=True)

bahrain_dl = bahrain_dl.replace({':':''}, regex=True)
bahrain_dl = bahrain_dl.replace({'s':''}, regex=True)
bahrain_dl = bahrain_dl.replace({'\+':''}, regex=True)
bahrain_dl = bahrain_dl.replace({'\.':''}, regex=True)

sakhir_dl = sakhir_dl.replace({':':''}, regex=True)
sakhir_dl = sakhir_dl.replace({'s':''}, regex=True)
sakhir_dl = sakhir_dl.replace({'\+':''}, regex=True)
sakhir_dl = sakhir_dl.replace({'\.':''}, regex=True)

ad_dl = ad_dl.replace({':':''}, regex=True)
ad_dl = ad_dl.replace({'s':''}, regex=True)
ad_dl = ad_dl.replace({'\+':''}, regex=True)
ad_dl = ad_dl.replace({'\.':''}, regex=True)

In [18]:
def no_5lap(race):
    race = race.replace(to_replace='5 lap', 
                value='0', inplace=True)

no_5lap(hungary_dl)

In [19]:
austria_dl = austria_dl.astype(int)
styria_dl = styria_dl.astype(int)
hungary_dl = hungary_dl.astype(int)
gb_dl = gb_dl.astype(int)
gb70_dl = gb70_dl.astype(int)
spain_dl = spain_dl.astype(int)
belgium_dl = belgium_dl.astype(int)
italy_dl = italy_dl.astype(int)
tuscany_dl = tuscany_dl.astype(int)
russia_dl = russia_dl.astype(int)
eifel_dl = eifel_dl.astype(int)
portugal_dl = portugal_dl.astype(int)
er_dl = er_dl.astype(int)
turkey_dl = turkey_dl.astype(int)
bahrain_dl = bahrain_dl.astype(int)
sakhir_dl = sakhir_dl.astype(int)
ad_dl = ad_dl.astype(int)

In [20]:
def drop_racetime(race):
    race.drop(race.columns[[-3, -2]], axis=1, inplace=True)
    
drop_racetime(austria_dl)

In [21]:
drop_racetime(styria_dl)
drop_racetime(hungary_dl)
drop_racetime(gb_dl)
drop_racetime(gb70_dl)
drop_racetime(spain_dl)
drop_racetime(belgium_dl)
drop_racetime(italy_dl)
drop_racetime(tuscany_dl)
drop_racetime(russia_dl)
drop_racetime(eifel_dl)
drop_racetime(portugal_dl)
drop_racetime(er_dl)
drop_racetime(turkey_dl)
drop_racetime(bahrain_dl)
drop_racetime(sakhir_dl)
drop_racetime(ad_dl)

In [22]:
all_races = [austria_dl,
styria_dl,
hungary_dl,
gb_dl,
gb70_dl,
spain_dl,
belgium_dl,
italy_dl,
tuscany_dl,
russia_dl,
eifel_dl,
portugal_dl,
er_dl,
turkey_dl,
bahrain_dl,
sakhir_dl,
ad_dl]

In [23]:
one = austria_dl[['austria_Pos1', 'austria_Pos2', 'austria_Pos3','austria_PosQ', 'austria_PosRR', 'austria_PTS_RR']]
austria_dl[['austria_Pos1', 'austria_Pos2', 'austria_Pos3','austria_PosQ', 'austria_PosRR', 'austria_PTS_RR']].corr()

,austria_Pos1,austria_Pos2,austria_Pos3,austria_PosQ,austria_PosRR,austria_PTS_RR
austria_Pos1,1.000000,0.760902,0.715789,0.843609,0.226426,-0.556530
austria_Pos2,0.760902,1.000000,0.798496,0.816541,0.116585,-0.537381
austria_Pos3,0.715789,0.798496,1.000000,0.914286,0.054920,-0.545759
austria_PosQ,0.843609,0.816541,0.914286,1.000000,0.124293,-0.633128
austria_PosRR,0.226426,0.116585,0.054920,0.124293,1.000000,-0.164261
austria_PTS_RR,-0.556530,-0.537381,-0.545759,-0.633128,-0.164261,1.000000

In [24]:
two = styria_dl[['styria_Pos1', 'styria_Pos2', 'styria_PosQ', 'styria_PosRR', 'styria_PTS_RR']]
styria_dl[['styria_Pos1', 'styria_Pos2', 'styria_PosQ', 'styria_PosRR', 'styria_PTS_RR']].corr()

,styria_Pos1,styria_Pos2,styria_PosQ,styria_PosRR,styria_PTS_RR
styria_Pos1,1.000000,0.253571,0.049055,-0.010703,-0.489860
styria_Pos2,0.253571,1.000000,0.671849,0.617219,-0.471165
styria_PosQ,0.049055,0.671849,1.000000,0.689379,-0.446237
styria_PosRR,-0.010703,0.617219,0.689379,1.000000,-0.394153
styria_PTS_RR,-0.489860,-0.471165,-0.446237,-0.394153,1.000000

In [25]:
three = hungary_dl[['hungary_Pos1', 'hungary_Pos2', 'hungary_Pos3','hungary_PosQ', 'hungary_PosRR', 'hungary_PTS_RR']]
hungary_dl[['hungary_Pos1', 'hungary_Pos2', 'hungary_Pos3','hungary_PosQ', 'hungary_PosRR', 'hungary_PTS_RR']].corr()

,hungary_Pos1,hungary_Pos2,hungary_Pos3,hungary_PosQ,hungary_PosRR,hungary_PTS_RR
hungary_Pos1,1.000000,0.278795,0.406356,0.357699,0.464680,-0.468613
hungary_Pos2,0.278795,1.000000,0.535065,0.522078,0.460274,-0.093677
hungary_Pos3,0.406356,0.535065,1.000000,0.954545,0.774575,-0.550078
hungary_PosQ,0.357699,0.522078,0.954545,1.000000,0.745644,-0.577309
hungary_PosRR,0.464680,0.460274,0.774575,0.745644,1.000000,-0.626341
hungary_PTS_RR,-0.468613,-0.093677,-0.550078,-0.577309,-0.626341,1.000000

In [26]:
four = gb_dl[['gb_Pos1', 'gb_Pos2', 'gb_Pos3','gb_PosQ', 'gb_PosRR', 'gb_PTS_RR']]
gb_dl[['gb_Pos1', 'gb_Pos2', 'gb_Pos3','gb_PosQ', 'gb_PosRR', 'gb_PTS_RR']].corr()

            gb_Pos1   gb_Pos2   gb_Pos3   gb_PosQ  gb_PosRR  gb_PTS_RR
gb_Pos1    1.000000  0.705263  0.783459  0.736842  0.567046  -0.640874
gb_Pos2    0.705263  1.000000  0.679699  0.607519  0.133745  -0.274490
gb_Pos3    0.783459  0.679699  1.000000  0.930827  0.434084  -0.570461
gb_PosQ    0.736842  0.607519  0.930827  1.000000  0.455983  -0.686224
gb_PosRR   0.567046  0.133745  0.434084  0.455983  1.000000  -0.526749
gb_PTS_RR -0.640874 -0.274490 -0.570461 -0.686224 -0.526749   1.000000

In [27]:
five = gb70_dl[['gb70_Pos1', 'gb70_Pos2', 'gb70_Pos3','gb70_PosQ', 'gb70_PosRR', 'gb70_PTS_RR']]
gb70_dl[['gb70_Pos1', 'gb70_Pos2', 'gb70_Pos3','gb70_PosQ', 'gb70_PosRR', 'gb70_PTS_RR']].corr()

,gb70_Pos1,gb70_Pos2,gb70_Pos3,gb70_PosQ,gb70_PosRR,gb70_PTS_RR
gb70_Pos1,1.000000,0.270130,0.429870,0.348052,0.251178,-0.669837
gb70_Pos2,0.270130,1.000000,0.871429,0.927273,0.648329,-0.584326
gb70_Pos3,0.429870,0.871429,1.000000,0.861039,0.657534,-0.576652
gb70_PosQ,0.348052,0.927273,0.861039,1.000000,0.660164,-0.586518
gb70_PosRR,0.251178,0.648329,0.657534,0.660164,1.000000,-0.629275
gb70_PTS_RR,-0.669837,-0.584326,-0.576652,-0.586518,-0.629275,1.000000

In [28]:
six = spain_dl[['spain_Pos1', 'spain_Pos2', 'spain_Pos3','spain_PosQ', 'spain_PosRR', 'spain_PTS_RR']]
spain_dl[['spain_Pos1', 'spain_Pos2', 'spain_Pos3','spain_PosQ', 'spain_PosRR', 'spain_PTS_RR']].corr()

,spain_Pos1,spain_Pos2,spain_Pos3,spain_PosQ,spain_PosRR,spain_PTS_RR
spain_Pos1,1.000000,0.231169,0.272727,0.259740,0.289315,-0.570564
spain_Pos2,0.231169,1.000000,0.889610,0.718182,0.711452,-0.530987
spain_Pos3,0.272727,0.889610,1.000000,0.896104,0.890302,-0.653015
spain_PosQ,0.259740,0.718182,0.896104,1.000000,0.919233,-0.698089
spain_PosRR,0.289315,0.711452,0.890302,0.919233,1.000000,-0.629916
spain_PTS_RR,-0.570564,-0.530987,-0.653015,-0.698089,-0.629916,1.000000

In [29]:
seven = belgium_dl[['belgium_Pos1', 'belgium_Pos2', 'belgium_Pos3','belgium_PosQ', 'belgium_PosRR', 'belgium_PTS_RR']]
belgium_dl[['belgium_Pos1', 'belgium_Pos2', 'belgium_Pos3','belgium_PosQ', 'belgium_PosRR', 'belgium_PTS_RR']].corr()

,belgium_Pos1,belgium_Pos2,belgium_Pos3,belgium_PosQ,belgium_PosRR,belgium_PTS_RR
belgium_Pos1,1.000000,0.849624,0.818045,0.926316,0.437212,-0.721365
belgium_Pos2,0.849624,1.000000,0.792481,0.915789,0.634310,-0.751372
belgium_Pos3,0.818045,0.792481,1.000000,0.818045,0.404363,-0.762174
belgium_PosQ,0.926316,0.915789,0.818045,1.000000,0.604589,-0.814986
belgium_PosRR,0.437212,0.634310,0.404363,0.604589,1.000000,-0.527271
belgium_PTS_RR,-0.721365,-0.751372,-0.762174,-0.814986,-0.527271,1.000000

In [30]:
eight = italy_dl[['italy_Pos1', 'italy_Pos2', 'italy_Pos3','italy_PosQ', 'italy_PosRR', 'italy_PTS_RR']]
italy_dl[['italy_Pos1', 'italy_Pos2', 'italy_Pos3','italy_PosQ', 'italy_PosRR', 'italy_PTS_RR']].corr()

,italy_Pos1,italy_Pos2,italy_Pos3,italy_PosQ,italy_PosRR,italy_PTS_RR
italy_Pos1,1.000000,0.316883,0.363636,0.412987,-0.113325,-0.266083
italy_Pos2,0.316883,1.000000,0.742857,0.819481,0.572439,-0.488927
italy_Pos3,0.363636,0.742857,1.000000,0.915584,0.457661,-0.407993
italy_PosQ,0.412987,0.819481,0.915584,1.000000,0.408262,-0.406885
italy_PosRR,-0.113325,0.572439,0.457661,0.408262,1.000000,-0.371560
italy_PTS_RR,-0.266083,-0.488927,-0.407993,-0.406885,-0.371560,1.000000

In [31]:
nine = tuscany_dl[['tuscany_Pos1', 'tuscany_Pos2', 'tuscany_Pos3','tuscany_PosQ', 'tuscany_PosRR', 'tuscany_PTS_RR']]
tuscany_dl[['tuscany_Pos1', 'tuscany_Pos2', 'tuscany_Pos3','tuscany_PosQ', 'tuscany_PosRR', 'tuscany_PTS_RR']].corr()

,tuscany_Pos1,tuscany_Pos2,tuscany_Pos3,tuscany_PosQ,tuscany_PosRR,tuscany_PTS_RR
tuscany_Pos1,1.000000,0.627068,0.499248,0.565414,0.039621,-0.416145
tuscany_Pos2,0.627068,1.000000,0.601504,0.836090,0.287777,-0.639038
tuscany_Pos3,0.499248,0.601504,1.000000,0.687218,0.389958,-0.368721
tuscany_PosQ,0.565414,0.836090,0.687218,1.000000,0.177254,-0.679348
tuscany_PosRR,0.039621,0.287777,0.389958,0.177254,1.000000,-0.070369
tuscany_PTS_RR,-0.416145,-0.639038,-0.368721,-0.679348,-0.070369,1.000000

In [32]:
ten = russia_dl[['russia_Pos1', 'russia_Pos2', 'russia_Pos3','russia_PosQ', 'russia_PosRR', 'russia_PTS_RR']]
russia_dl[['russia_Pos1', 'russia_Pos2', 'russia_Pos3','russia_PosQ', 'russia_PosRR', 'russia_PTS_RR']].corr()

,russia_Pos1,russia_Pos2,russia_Pos3,russia_PosQ,russia_PosRR,russia_PTS_RR
russia_Pos1,1.000000,0.463158,0.437594,0.562406,0.653288,-0.543004
russia_Pos2,0.463158,1.000000,0.590977,0.857143,0.598403,-0.691204
russia_Pos3,0.437594,0.590977,1.000000,0.685714,0.741714,-0.639038
russia_PosQ,0.562406,0.857143,0.685714,1.000000,0.721895,-0.756412
russia_PosRR,0.653288,0.598403,0.741714,0.721895,1.000000,-0.621567
russia_PTS_RR,-0.543004,-0.691204,-0.639038,-0.756412,-0.621567,1.000000

In [33]:
eleven = eifel_dl[['eifel_Pos1', 'eifel_PosQ', 'eifel_PosRR', 'eifel_PTS_RR']]
eifel_dl[['eifel_Pos1', 'eifel_PosQ', 'eifel_PosRR', 'eifel_PTS_RR']].corr()

              eifel_Pos1  eifel_PosQ  eifel_PosRR  eifel_PTS_RR
eifel_Pos1      1.000000    0.609023     0.442141     -0.433216
eifel_PosQ      0.609023    1.000000     0.658110     -0.501242
eifel_PosRR     0.442141    0.658110     1.000000     -0.345500
eifel_PTS_RR   -0.433216   -0.501242    -0.345500      1.000000

In [34]:
twelve = portugal_dl[['portugal_Pos1', 'portugal_Pos2', 'portugal_Pos3','portugal_PosQ', 'portugal_PosRR', 'portugal_PTS_RR']]
portugal_dl[['portugal_Pos1', 'portugal_Pos2', 'portugal_Pos3','portugal_PosQ', 'portugal_PosRR', 'portugal_PTS_RR']].corr()

,portugal_Pos1,portugal_Pos2,portugal_Pos3,portugal_PosQ,portugal_PosRR,portugal_PTS_RR
portugal_Pos1,1.000000,0.619549,0.834586,0.833083,0.643609,-0.726772
portugal_Pos2,0.619549,1.000000,0.809023,0.720301,0.526316,-0.612955
portugal_Pos3,0.834586,0.809023,1.000000,0.918797,0.690226,-0.783681
portugal_PosQ,0.833083,0.720301,0.918797,1.000000,0.759398,-0.783681
portugal_PosRR,0.643609,0.526316,0.690226,0.759398,1.000000,-0.727958
portugal_PTS_RR,-0.726772,-0.612955,-0.783681,-0.783681,-0.727958,1.000000

In [35]:
thirteen = er_dl[['er_Pos1', 'er_PosQ', 'er_PosRR', 'er_PTS_RR']]
er_dl[['er_Pos1', 'er_PosQ', 'er_PosRR', 'er_PTS_RR']].corr()

            er_Pos1   er_PosQ  er_PosRR  er_PTS_RR
er_Pos1    1.000000  0.846617  0.387724  -0.557232
er_PosQ    0.846617  1.000000  0.479553  -0.616512
er_PosRR   0.387724  0.479553  1.000000  -0.344572
er_PTS_RR -0.557232 -0.616512 -0.344572   1.000000

In [36]:
fourteen = turkey_dl[['turkey_Pos1', 'turkey_Pos2', 'turkey_Pos3','turkey_PosQ', 'turkey_PosRR', 'turkey_PTS_RR']]
turkey_dl[['turkey_Pos1', 'turkey_Pos2', 'turkey_Pos3','turkey_PosQ', 'turkey_PosRR', 'turkey_PTS_RR']].corr()

,turkey_Pos1,turkey_Pos2,turkey_Pos3,turkey_PosQ,turkey_PosRR,turkey_PTS_RR
turkey_Pos1,1.000000,0.711278,0.563910,0.148872,0.213522,-0.096766
turkey_Pos2,0.711278,1.000000,0.476692,0.454135,0.071174,-0.445126
turkey_Pos3,0.563910,0.476692,1.000000,0.475188,0.005475,-0.156036
turkey_PosQ,0.148872,0.454135,0.475188,1.000000,0.049274,-0.347150
turkey_PosRR,0.213522,0.071174,0.005475,0.049274,1.000000,-0.526326
turkey_PTS_RR,-0.096766,-0.445126,-0.156036,-0.347150,-0.526326,1.000000

In [37]:
fifteen = bahrain_dl[['bahrain_Pos1', 'bahrain_Pos2', 'bahrain_Pos3','bahrain_PosQ', 'bahrain_PosRR', 'bahrain_PTS_RR']] 
bahrain_dl[['bahrain_Pos1', 'bahrain_Pos2', 'bahrain_Pos3','bahrain_PosQ', 'bahrain_PosRR', 'bahrain_PTS_RR']].corr()

,bahrain_Pos1,bahrain_Pos2,bahrain_Pos3,bahrain_PosQ,bahrain_PosRR,bahrain_PTS_RR
bahrain_Pos1,1.000000,0.061765,0.114916,0.187710,-0.041717,-0.346582
bahrain_Pos2,0.061765,1.000000,0.877521,0.916807,0.506031,-0.430506
bahrain_Pos3,0.114916,0.877521,1.000000,0.862500,0.676441,-0.558439
bahrain_PosQ,0.187710,0.916807,0.862500,1.000000,0.480469,-0.449952
bahrain_PosRR,-0.041717,0.506031,0.676441,0.480469,1.000000,-0.470962
bahrain_PTS_RR,-0.346582,-0.430506,-0.558439,-0.449952,-0.470962,1.000000

In [38]:
sixteen = sakhir_dl[['sakhir_Pos1', 'sakhir_Pos2', 'sakhir_Pos3','sakhir_PosQ', 'sakhir_PosRR', 'sakhir_PTS_RR']]
sakhir_dl[['sakhir_Pos1', 'sakhir_Pos2', 'sakhir_Pos3','sakhir_PosQ', 'sakhir_PosRR', 'sakhir_PTS_RR']].corr()

,sakhir_Pos1,sakhir_Pos2,sakhir_Pos3,sakhir_PosQ,sakhir_PosRR,sakhir_PTS_RR
sakhir_Pos1,1.000000,0.720301,0.721805,0.780451,0.398106,-0.175732
sakhir_Pos2,0.720301,1.000000,0.631579,0.586466,0.457548,-0.580520
sakhir_Pos3,0.721805,0.631579,1.000000,0.654135,0.427827,-0.302985
sakhir_PosQ,0.780451,0.586466,0.654135,1.000000,0.592075,-0.333284
sakhir_PosRR,0.398106,0.457548,0.427827,0.592075,1.000000,-0.526093
sakhir_PTS_RR,-0.175732,-0.580520,-0.302985,-0.333284,-0.526093,1.000000

In [39]:
seventeen = ad_dl[['ad_Pos1', 'ad_Pos2', 'ad_Pos3','ad_PosQ', 'ad_PosRR', 'ad_PTS_RR']]
ad_dl[['ad_Pos1', 'ad_Pos2', 'ad_Pos3','ad_PosQ', 'ad_PosRR', 'ad_PTS_RR']].corr()

            ad_Pos1   ad_Pos2   ad_Pos3   ad_PosQ  ad_PosRR  ad_PTS_RR
ad_Pos1    1.000000  0.196954  0.054832  0.190021  0.120843  -0.396980
ad_Pos2    0.196954  1.000000  0.882143  0.890231  0.903534  -0.537710
ad_Pos3    0.054832  0.882143  1.000000  0.838235  0.850410  -0.487006
ad_PosQ    0.190021  0.890231  0.838235  1.000000  0.812633  -0.585310
ad_PosRR   0.120843  0.903534  0.850410  0.812633  1.000000  -0.549664
ad_PTS_RR -0.396980 -0.537710 -0.487006 -0.585310 -0.549664   1.000000

In [41]:
races_combined = races_combined.join(three)

In [42]:
races_combined = races_combined.join(four)
races_combined = races_combined.join(five)
races_combined = races_combined.join(six)
races_combined = races_combined.join(seven)
races_combined = races_combined.join(eight)
races_combined = races_combined.join(nine)
races_combined = races_combined.join(ten)
races_combined = races_combined.join(eleven)
races_combined = races_combined.join(twelve)
races_combined = races_combined.join(thirteen)
races_combined = races_combined.join(fourteen)
races_combined = races_combined.join(fifteen)
races_combined = races_combined.join(sixteen)
races_combined = races_combined.join(seventeen)

In [ ]:
# races_combined['RR_Combined'] = races_combined['austria_PTS_RR'] + races_combined['styria_PTS_RR'] + races_combined['hungary_PTS_RR'] + races_combined['gb_PTS_RR'] + races_combined['gb70_PTS_RR'] + races_combined['spain_PTS_RR'] + races_combined['belgium_PTS_RR'] + races_combined['italy_PTS_RR'] + races_combined['tuscany_PTS_RR'] + races_combined['russia_PTS_RR'] + races_combined['eifel_PTS_RR'] + races_combined['portugal_PTS_RR'] + races_combined['er_PTS_RR'] + races_combined['turkey_PTS_RR'] + races_combined['bahrain_PTS_RR'] + races_combined['sakhir_PTS_RR'] + races_combined['ad_PTS_RR']

In [44]:
races_PTS = races_combined[['austria_PTS_RR', 'styria_PTS_RR', 'hungary_PTS_RR','gb_PTS_RR', 'gb70_PTS_RR', 'spain_PTS_RR', 'belgium_PTS_RR','italy_PTS_RR', 'tuscany_PTS_RR', 'russia_PTS_RR', 'eifel_PTS_RR', 'portugal_PTS_RR', 'er_PTS_RR', 'turkey_PTS_RR', 'bahrain_PTS_RR', 'sakhir_PTS_RR','ad_PTS_RR']].corr()
races_combined[['austria_PTS_RR', 'styria_PTS_RR', 'hungary_PTS_RR','gb_PTS_RR', 'gb70_PTS_RR', 'spain_PTS_RR', 'belgium_PTS_RR','italy_PTS_RR', 'tuscany_PTS_RR', 'russia_PTS_RR', 'eifel_PTS_RR', 'portugal_PTS_RR', 'er_PTS_RR', 'turkey_PTS_RR', 'bahrain_PTS_RR', 'sakhir_PTS_RR','ad_PTS_RR']].corr()

,austria_PTS_RR,styria_PTS_RR,hungary_PTS_RR,gb_PTS_RR,gb70_PTS_RR,spain_PTS_RR,belgium_PTS_RR,italy_PTS_RR,tuscany_PTS_RR,russia_PTS_RR,eifel_PTS_RR,portugal_PTS_RR,er_PTS_RR,turkey_PTS_RR,bahrain_PTS_RR,sakhir_PTS_RR,ad_PTS_RR
austria_PTS_RR,1.000000,0.628715,0.243264,0.237273,0.549774,0.630406,0.380017,0.044006,0.493323,0.552770,0.419645,0.625429,0.577304,0.322313,0.009309,0.215873,0.453322
styria_PTS_RR,0.628715,1.000000,0.683963,0.243152,0.758697,0.841887,0.450592,0.059156,0.662942,0.308443,0.484574,0.278822,0.408773,0.258140,0.518238,0.242039,0.812226
hungary_PTS_RR,0.243264,0.683963,1.000000,0.320669,0.609535,0.792449,0.220304,-0.071576,0.498972,-0.018882,0.586953,0.063376,0.250327,0.480455,0.293382,0.388707,0.352932
gb_PTS_RR,0.237273,0.243152,0.320669,1.000000,0.332260,0.197379,0.688523,-0.284748,0.455223,0.471218,0.449706,0.618004,0.477805,0.522988,0.032961,-0.023276,-0.083546
gb70_PTS_RR,0.549774,0.758697,0.609535,0.332260,1.000000,0.846128,0.558020,0.276700,0.709274,0.264213,0.637242,0.468396,0.589776,0.369394,0.305740,0.103686,0.466404
spain_PTS_RR,0.630406,0.841887,0.792449,0.197379,0.846128,1.000000,0.393391,0.202544,0.590515,0.273460,0.644759,0.345175,0.460296,0.414733,0.311361,0.303650,0.560936
belgium_PTS_RR,0.380017,0.450592,0.220304,0.688523,0.558020,0.393391,1.000000,-0.124496,0.745514,0.767280,0.361789,0.748353,0.644258,0.326134,0.051249,0.063652,0.076895
italy_PTS_RR,0.044006,0.059156,-0.071576,-0.284748,0.276700,0.202544,-0.124496,1.000000,-0.129637,-0.129637,0.186638,-0.150577,-0.021130,-0.247816,0.353348,0.028994,0.260516
tuscany_PTS_RR,0.493323,0.662942,0.498972,0.455223,0.709274,0.590515,0.745514,-0.129637,1.000000,0.606468,0.434522,0.572817,0.829875,0.490945,0.027099,0.213846,0.232052
russia_PTS_RR,0.552770,0.308443,-0.018882,0.471218,0.264213,0.273460,0.767280,-0.129637,0.606468,1.000000,0.066618,0.785007,0.665358,0.311657,-0.166733,0.132627,0.022653
eifel_PTS_RR,0.419645,0.484574,0.586953,0.449706,0.637242,0.644759,0.361789,0.186638,0.434522,0.066618,1.000000,0.244454,0.462750,0.428912,0.157984,0.153702,0.247957
portugal_PTS_RR,0.625429,0.278822,0.063376,0.618004,0.468396,0.345175,0.748353,-0.150577,0.572817,0.785007,0.244454,1.000000,0.678445,0.571053,-0.203429,-0.080455,-0.106793
er_PTS_RR,0.577304,0.408773,0.250327,0.477805,0.589776,0.460296,0.644258,-0.021130,0.829875,0.665358,0.462750,0.678445,1.000000,0.466150,-0.177083,0.125938,0.024557
turkey_PTS_RR,0.322313,0.258140,0.480455,0.522988,0.369394,0.414733,0.326134,-0.247816,0.490945,0.311657,0.428912,0.571053,0.466150,1.000000,-0.099068,0.202574,-0.203147
bahrain_PTS_RR,0.009309,0.518238,0.293382,0.032961,0.305740,0.311361,0.051249,0.353348,0.027099,-0.166733,0.157984,-0.203429,-0.177083,-0.099068,1.000000,0.112343,0.679102
sakhir_PTS_RR,0.215873,0.242039,0.388707,-0.023276,0.103686,0.303650,0.063652,0.028994,0.213846,0.132627,0.153702,-0.080455,0.125938,0.202574,0.112343,1.000000,0.033859
ad_PTS_RR,0.453322,0.812226,0.352932,-0.083546,0.466404,0.560936,0.076895,0.260516,0.232052,0.022653,0.247957,-0.106793,0.024557,-0.203147,0.679102,0.033859,1.000000

In [ ]:
profile = ProfileReport(races_PTS, title='Points Report', html={'style':{'full_width': True}})
profile

In [62]:
races_combined

,austria_Pos1,austria_Pos2,austria_Pos3,austria_PosQ,austria_PosRR,austria_PTS_RR,styria_Pos1,styria_Pos2,styria_PosQ,styria_PosRR,...,sakhir_Pos3,sakhir_PosQ,sakhir_PosRR,sakhir_PTS_RR,ad_Pos1,ad_Pos2,ad_Pos3,ad_PosQ,ad_PosRR,ad_PTS_RR
0,7,13,6,5,13,0,6,7,7,4,...,6,12,6,8,4,4,2,5,4,12
1,14,14,18,18,9,2,7,5,3,9,...,11,14,13,0,11,12,8,6,6,8
2,4,10,13,8,5,10,12,9,11,0,...,10,8,4,12,12,8,12,9,13,0
3,10,9,5,7,2,18,9,20,9,8,...,13,4,0,0,20,9,3,12,7,7
4,8,5,12,10,0,0,11,12,14,10,...,14,7,5,10,8,11,11,7,11,0
5,19,12,14,13,12,0,13,10,5,0,...,12,6,7,6,3,6,4,11,9,2
6,13,11,11,14,8,4,17,0,0,0,...,4,11,2,18,16,18,15,18,15,0
7,17,18,16,17,0,0,20,18,15,12,...,7,2,9,3,10,14,17,16,12,0
8,9,15,17,16,0,0,15,13,16,11,...,20,18,16,0,6,10,7,8,10,1
9,15,19,19,19,0,0,5,4,13,7,...,17,16,15,0,13,5,5,4,5,10
10,11,7,8,9,0,0,14,8,6,5,...,16,19,14,0,5,2,6,3,3,15
11,6,6,10,4,3,16,4,6,1,1,...,9,10,3,15,1,3,1,1,1,25
12,1,1,1,2,4,12,2,1,2,3,...,5,15,10,1,18,0,0,0,0,0
13,3,8,3,3,0,0,19,17,18,17,...,1,3,0,0,17,20,19,20,17,0
14,18,20,20,20,11,0,8,11,8,15,...,18,17,0,0,9,13,13,10,8,4
15,16,17,9,12,7,6,18,0,0,0,...,3,9,11,0,19,19,20,19,19,0
16,20,16,15,15,0,0,16,19,20,13,...,19,20,17,0,15,0,0,0,0,0
17,12,4,7,11,10,1,10,16,10,0,...,15,13,12,0,14,15,14,13,14,0
18,5,3,4,6,6,8,1,3,17,6,...,8,5,1,25,7,7,10,15,0,0
19,2,2,2,1,1,25,3,2,4,2,...,2,1,8,4,2,1,9,2,2,18

In [64]:
races_combined.columns

Index(['austria_Pos1', 'austria_Pos2', 'austria_Pos3', 'austria_PosQ',
       'austria_PosRR', 'austria_PTS_RR', 'styria_Pos1', 'styria_Pos2',
       'styria_PosQ', 'styria_PosRR', 'styria_PTS_RR', 'hungary_Pos1',
       'hungary_Pos2', 'hungary_Pos3', 'hungary_PosQ', 'hungary_PosRR',
       'hungary_PTS_RR', 'gb_Pos1', 'gb_Pos2', 'gb_Pos3', 'gb_PosQ',
       'gb_PosRR', 'gb_PTS_RR', 'gb70_Pos1', 'gb70_Pos2', 'gb70_Pos3',
       'gb70_PosQ', 'gb70_PosRR', 'gb70_PTS_RR', 'spain_Pos1', 'spain_Pos2',
       'spain_Pos3', 'spain_PosQ', 'spain_PosRR', 'spain_PTS_RR',
       'belgium_Pos1', 'belgium_Pos2', 'belgium_Pos3', 'belgium_PosQ',
       'belgium_PosRR', 'belgium_PTS_RR', 'italy_Pos1', 'italy_Pos2',
       'italy_Pos3', 'italy_PosQ', 'italy_PosRR', 'italy_PTS_RR',
       'tuscany_Pos1', 'tuscany_Pos2', 'tuscany_Pos3', 'tuscany_PosQ',
       'tuscany_PosRR', 'tuscany_PTS_RR', 'russia_Pos1', 'russia_Pos2',
       'russia_Pos3', 'russia_PosQ', 'russia_PosRR', 'russia_PTS_RR',
       'eifel_Pos1', 'eifel_PosQ', 'eifel_PosRR', 'eifel_PTS_RR',
       'portugal_Pos1', 'portugal_Pos2', 'portugal_Pos3', 'portugal_PosQ',
       'portugal_PosRR', 'portugal_PTS_RR', 'er_Pos1', 'er_PosQ', 'er_PosRR',
       'er_PTS_RR', 'turkey_Pos1', 'turkey_Pos2', 'turkey_Pos3', 'turkey_PosQ',
       'turkey_PosRR', 'turkey_PTS_RR', 'bahrain_Pos1', 'bahrain_Pos2',
       'bahrain_Pos3', 'bahrain_PosQ', 'bahrain_PosRR', 'bahrain_PTS_RR',
       'sakhir_Pos1', 'sakhir_Pos2', 'sakhir_Pos3', 'sakhir_PosQ',
       'sakhir_PosRR', 'sakhir_PTS_RR', 'ad_Pos1', 'ad_Pos2', 'ad_Pos3',
       'ad_PosQ', 'ad_PosRR', 'ad_PTS_RR'],
      dtype='object')

In [98]:
df_model = races_combined[['austria_PosRR', 'styria_PosRR', 'hungary_PosRR', 'gb_PosRR', 'gb70_PosRR', 'spain_PosRR', 'belgium_PosRR', 'italy_PosRR', 'tuscany_PosRR', 'russia_PosRR', 'eifel_PosRR', 'portugal_PosRR', 'er_PosRR', 'turkey_PosRR', 'bahrain_PosRR', 'sakhir_PosRR', 'ad_PosRR']]

In [101]:
from sklearn.model_selection import train_test_split

X = df_model.drop('ad_PosRR', axis=1)
y = df_model.ad_PosRR.values

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=.2, random_state=42)

In [102]:
import statsmodels.api as sm

X_sm = X = sm.add_constant(X)
model = sm.OLS(y, X_sm)
model.fit().summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                      y   R-squared:                       0.951
Model:                            OLS   Adj. R-squared:                  0.687
Method:                 Least Squares   F-statistic:                     3.606
Date:                Wed, 28 Apr 2021   Prob (F-statistic):              0.159
Time:                        18:21:13   Log-Likelihood:                -33.468
No. Observations:                  20   AIC:                             100.9
Df Residuals:                       3   BIC:                             117.9
Df Model:                          16
Covariance Type:            nonrobust
==================================================================================
                     coef    std err          t      P>|t|      [0.025      0.975]
----------------------------------------------------------------------------------
const              8.9629      4.499      1.992      0.140      -5.354      23.280
austria_PosRR      0.5099      0.513      0.994      0.394      -1.123       2.143
styria_PosRR      -0.0930      0.342     -0.272      0.803      -1.181       0.995
hungary_PosRR     -0.0382      0.266     -0.144      0.895      -0.883       0.807
gb_PosRR           0.2943      0.301      0.979      0.400      -0.662       1.251
gb70_PosRR         0.6013      0.287      2.097      0.127      -0.311       1.514
spain_PosRR        0.6587      0.375      1.757      0.177      -0.535       1.852
belgium_PosRR     -0.4707      0.340     -1.384      0.260      -1.553       0.612
italy_PosRR       -0.3856      0.298     -1.294      0.286      -1.334       0.563
tuscany_PosRR      0.9943      0.566      1.756      0.177      -0.807       2.796
russia_PosRR      -0.2272      0.406     -0.560      0.614      -1.518       1.064
eifel_PosRR       -0.0329      0.297     -0.111      0.919      -0.979       0.913
portugal_PosRR     0.0924      0.314      0.294      0.788      -0.907       1.092
er_PosRR          -0.8163      0.595     -1.373      0.263      -2.708       1.076
turkey_PosRR      -0.2250      0.342     -0.659      0.557      -1.312       0.862
bahrain_PosRR     -0.8491      0.385     -2.207      0.114      -2.073       0.375
sakhir_PosRR       0.0487      0.290      0.168      0.877      -0.874       0.971
==============================================================================
Omnibus:                        1.675   Durbin-Watson:                   1.368
Prob(Omnibus):                  0.433   Jarque-Bera (JB):                1.151
Skew:                           0.576   Prob(JB):                        0.563
Kurtosis:                       2.772   Cond. No.                         186.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [126]:
from sklearn.linear_model import LinearRegression, Lasso
from sklearn.model_selection import cross_val_score

In [124]:
lm = LinearRegression()
lm.fit(X_train, y_train)
np.mean(cross_val_score(lm, X_train, y_train, scoring = 'neg_mean_absolute_error'))

-6.465414743055815

In [125]:
lm_l = Lasso()
np.mean(cross_val_score(lm_l, X_train, y_train, scoring = 'neg_mean_absolute_error'))

-4.086864695908323